### PR TITLE
Relicense and Maven publishing

### PR DESCRIPTION
**Pull request by ramidzkh**
We require written permission of all non-trivial contributors here. Please post that you permit Kiln Graphics to relicense Blaze4D to LGPLv3 below.

@burgerguy 
@hYdos
@OroArmor
@CodingRays

### CODE REVIEW

**Comment by OroArmor** [comment]
run `gradlew updateLicenses`

**Review by burgerguy — APPROVED** [review]

**Comment by hYdos** [comment]
Waiting for oro's suggestion before i approve

**Comment by ramidzkh** [comment]
> 
> 
> run `gradlew updateLicenses`

We don't have that task..?

**Review by hYdos — APPROVED** [review]

**Comment by OroArmor** [comment]
oh, i thought we did. we did at one point. all good

**Review by OroArmor — APPROVED** [review]

**Review by CodingRays — APPROVED** [review]

**Comment by OroArmor** [comment]
@ramidzkh thats everyone

**Comment by OroArmor** [comment]
Wait I can merge

**Pull request merged**
